=== skopp1974/DjyangoRest/RestInjestion2/RestInj2/RigTest/rigschema.json
{
   "definitions": {},
   "$schema": "http://json-schema.org/draft-07/schema#",
   "$id": "http://example.com/root.json",
   "type": "object",
   "title": "The Root Schema",
   "required": [
     "id",
     "rig_name",
     "rig_location",
     "well_bore_diameter",
     "well_name",
     "well_location",
     "well_diameter",
     "well_depth",
     "raw_data"
   ],
   "properties": {
     "id": {
       "$id": "#/properties/id",
       "type": "string",
       "title": "The Id Schema",
       "default": "",
       "examples": [
         "1"
       ],
       "pattern": "^(.*)$"
     },
     "rig_name": {
       "$id": "#/properties/rig_name",
       "type": "string",
       "title": "The Rig_name Schema",
       "default": "",
       "examples": [
         "HoustonRig"
       ],
       "pattern": "^(.*)$"
     },
     "rig_location": {
       "$id": "#/properties/rig_location",
       "type": "string",
       "title": "The Rig_location Schema",
       "default": "",
       "examples": [
         "Houston"
       ],
       "pattern": "^(.*)$"
     },
     "well_bore_diameter": {
       "$id": "#/properties/well_bore_diameter",
       "type": "string",
       "title": "The Well_bore_diameter Schema",
       "default": "",
       "examples": [
         "100"
       ],
       "pattern": "^(.*)$"
     },
     "well_name": {
       "$id": "#/properties/well_name",
       "type": "string",
       "title": "The Well_name Schema",
       "default": "",
       "examples": [
         "well1"
       ],
       "pattern": "^(.*)$"
     },
     "well_location": {
       "$id": "#/properties/well_location",
       "type": "string",
       "title": "The Well_location Schema",
       "default": "",
       "examples": [
         "Houston"
       ],
       "pattern": "^(.*)$"
     },
     "well_diameter": {
       "$id": "#/properties/well_diameter",
       "type": "string",
       "title": "The Well_diameter Schema",
       "default": "",
       "examples": [
         "90"
       ],
       "pattern": "^(.*)$"
     },
     "well_depth": {
       "$id": "#/properties/well_depth",
       "type": "string",
       "title": "The Well_depth Schema",
       "default": "",
       "examples": [
         "1000"
       ],
       "pattern": "^(.*)$"
     },
     "raw_data": {
       "$id": "#/properties/raw_data",
       "type": "string",
       "title": "The Raw_data Schema",
       "default": "",
       "examples": [
         "c:\\Users\\srinik\\RestTest\\DJango\\RestInjestion2\\RestInj2\\RigTest\\RawData\\1.dat"
       ],
       "pattern": "^(.*)$"
     }
   }
 }

=== skopp1974/DjyangoRest/RestInjestion2/RestInj2/RigTest/samplerecord.json
{
    "id":"1",
    "rig_name": "HoustonRig",
    "rig_location": "Houston",
    "well_bore_diameter": "100",
    "well_name": "well1", 
    "well_location": "Houston",
    "well_diameter": "90",
    "well_depth": "1000",
    "raw_data": "c:\\Users\\srinik\\RestTest\\DJango\\RestInjestion2\\RestInj2\\RigTest\\RawData\\1.dat"
}
